apiVersion: v1
kind: Service
metadata:
  name: mvn-hello-world-service
spec:
  selector:
    app: mvn-hello-world
  ports:
    - protocol: TCP
      port: 8086  # Port exposed by the service
      targetPort: 8080  # Port on the container to forward requests to
  type: NodePort  # Exposes the service on a port on each node in the cluster
